### ISSUE TITLE
配置分享链接怎么显示成Localhost

### ISSUE THREAD

**Issue by shylock-wu** [k0baya/cloudreve-freebsd#1]
好像没有配置这个地方的配置？

![CleanShot 2024-08-08 at 11 18 46@2x](https://github.com/user-attachments/assets/54a88fbf-1758-412d-985f-3638ecb7ca4e)

**Comment by k0baya** [comment]
本仓库只提供构建，没有对 cloudreve 源代码作任何修改。关于 cloudreve 的使用问题，请移步 cloudreve 原仓库：https://github.com/cloudreve/Cloudreve

另外你的问题，早在原仓库的 issue 内有解答：[#922](https://github.com/cloudreve/Cloudreve/issues/922)

**Comment by shylock-wu** [comment]
thanks

**Comment by shylock-wu** [comment]
> 本仓库只提供构建，没有对 cloudreve 源代码作任何修改。关于 cloudreve 的使用问题，请移步 cloudreve 原仓库：https://github.com/cloudreve/Cloudreve
> 
> 另外你的问题，早在原仓库的 issue 内有解答：[#922](https://github.com/cloudreve/Cloudreve/issues/922)

创建的没有这个界面啊 大佬
![CleanShot 2024-08-08 at 20 06 28@2x](https://github.com/user-attachments/assets/72464c7b-1067-48cd-8dc3-30d2ed6a58bb)
